version: '3.7'
services:
  rabbit:
    image: rabbitmq:3-management
    env_file: .env
    expose:
      - "15672"
      - "5671"
    ports:
      - "5672:5672"
  elasticsearch:
       image: elasticsearch:7.6.2
       env_file: .env
       expose:
         - "9200"
         - "9300"
       ports:
         - "9200:9200"
       volumes:
         - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
         - es_data:/usr/share/elasticsearch/data
         - /data/elastic_backups:/backups

  pselastic_setup:
    image: perfsonar/pselastic_setup:latest
    env_file: .env
    depends_on: 
     - elasticsearch
    volumes:
       - ./pselastic_setup:/app

  logstash:
       image: logstash:7.6.2
       env_file: .env
       depends_on: 
        - pselastic_setup
       expose:
         - "5044"
         - "9600"
       volumes:
           - ./logstash_pipeline/pipeline:/usr/share/logstash/pipeline/
           - ./logstash_pipeline/pipelines.yml:/usr/share/logstash/config/pipelines.yml
  kibana:
       image: kibana:7.6.2
       env_file: .env
       ports:
         - "5601:5601"

volumes:
  es_data:
    driver: local
