version: '3.7'
services:
   elmond:         
       image: perfsonar/elmond:latest
       env_file: .env
       build:
          context: elmond
          dockerfile: Dockerfile
   ps_elastic_setup:         
       image: perfsonar/ps_elastic_setup:latest
       env_file: .env
       build:
          context: ps_elastic_setup
          dockerfile: Dockerfile
